sudo: required
dist: trusty
language: node_js
node_js:
  - "5"
env:
  - NODE_ENV=ci
cache:
  directories:
  - node_modules
  - jspm_packages
  - /usr/local/lib/node_modules
install:
  - npm install
  - jspm install
  - typings install
  - npm run compile

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install gulp typings jspm -g

script:
  - npm run compile
  - npm run test
  - gulp tslint
# Travis CI config
