language: node_js
node_js:
  - "5"
env:
  - NODE_ENV=ci
cache:
  directories:
  - node_modules
  - jspm_packages
install:
  - npm install
  - jspm install
  - tsd reinstall
  - npm run compile

before_install:
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=chromium-browser
  - npm install gulp tsd typings jspm -g

script:
  - npm run build
  - npm run test
# Travis CI config
