language: node_js
node_js:
  - "5"
env:
  - NODE_ENV=ci
cache:
  directories:
  - node_modules
install:
  - npm install
  - jspm install
  - tsd reinstall
  - npm run compile

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install gulp tsd typings jspm -g

script:
  - npm run build
  - npm run test
# Travis CI config
