name: documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Test Build
        run: |
          cd docs
          npm ci
          npm run build
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: setup git remote
        run: echo "machine github.com login ${{ secrets.GH_USER }} password ${{ secrets.GH_TOKEN }}" > ~/.netrc
      - name: Release to GitHub Pages
        env:
          USE_SSH: false
          GIT_USER: ${{ secrets.GH_USER }}
        run: |
          cd docs
          ls
          git config --global user.email "dev@crazy-factory.com"
          git config --global user.name "${{ secrets.GH_USER }}"
          npm ci
          npx docusaurus deploy
